/**
 * Generated by ramidzkh's awesome generator thingy
 */
package me.hwiggy.whmjava.payload.g;

import me.hwiggy.whmjava.payload.Payload;

/**
 * This class and its methods directly relate to the API documentation.
 * API documentation can be found at the￼ following URL:
 ￼* https://developers.whmcs.com/api-reference/getcredits/
 */
public class GetCreditsPayload extends Payload {

    /***
     * Obtain the Credit Log for a Client Account
     * @param clientid The Client to obtain the log for
     */
    public GetCreditsPayload(int clientid) {
        super ("GetCredits");
        put("clientid", clientid);
    }
}