/**
 * Generated by ramidzkh's awesome generator thingy
 */
package me.hwiggy.whmjava.payload.g;

import me.hwiggy.whmjava.payload.Payload;

/**
 * This class and its methods directly relate to the API documentation.
 * API documentation can be found at the￼ following URL:
 ￼* https://developers.whmcs.com/api-reference/getclientsaddons/
 */
public class GetClientsAddonsPayload extends Payload {

    /*
     * Obtain the Clients Product Addons that match passed criteria
     */
    public GetClientsAddonsPayload() {
        super ("GetClientsAddons");
    }

    /***
     *
     * @param serviceID The service id(s) to obtain the client product addons for. Single number or comma separated list
     */
    public GetClientsAddonsPayload withServiceID(int serviceID) {
        put("serviceid", serviceID);

        return this;
    }

    /***
     *
     * @param clientID The client to obtain the client product addons for
     */
    public GetClientsAddonsPayload withClientid(int clientID) {
        put("clientid", clientID);

        return this;
    }

    /***
     *
     * @param addonID The predefined addon id to obtain the client product addons for
     */
    public GetClientsAddonsPayload withAddonid(int addonID) {
        put("addonid", addonID);

        return this;
    }
}