/**
 * Generated by ramidzkh's awesome generator thingy
 */
package me.hwiggy.whmjava.payload.g;

import me.hwiggy.whmjava.payload.Payload;

/**
 * This class and its methods directly relate to the API documentation.
 * API documentation can be found at the￼ following URL:
 ￼* https://developers.whmcs.com/api-reference/getclientsproducts/
 */
public class GetClientsProductsPayload extends Payload {

    /*
     * Obtain a list of Client Purchased Products matching the provided criteria
     */
    public GetClientsProductsPayload() {
        super ("GetClientsProducts");
    }

    /***
     *
     * @param limitStart  The offset for the returned log data (default: 0)
     */
    public GetClientsProductsPayload withLimitStart(int limitStart) {
        put("limitstart", limitStart);

        return this;
    }

    /***
     *
     * @param limitNum  The number of records to return (default: 25)
     */
    public GetClientsProductsPayload withLimitNum(int limitNum) {
        put("limitnum", limitNum);

        return this;
    }

    /***
     *
     * @param clientID  The client id to obtain the details for.
     */
    public GetClientsProductsPayload withClientID(int clientID) {
        put("clientid", clientID);

        return this;
    }

    /***
     *
     * @param serviceID The specific service id to obtain the details for
     */
    public GetClientsProductsPayload withServiceID(int serviceID) {
        put("serviceid", serviceID);

        return this;
    }

    /***
     *
     * @param pID  The specific product id to obtain the details for
     */
    public GetClientsProductsPayload withPID(int pID) {
        put("pid", pID);

        return this;
    }

    /***
     *
     * @param domain The specific domain to obtain the service details for
     */
    public GetClientsProductsPayload withDomain(String domain) {
        put("domain", domain);

        return this;
    }

    /***
     *
     * @param username2  The specific username to obtain the details for
     */
    public GetClientsProductsPayload withUsername2(String username2) {
        put("username2", username2);

        return this;
    }
}