/**
 * Generated by ramidzkh's awesome generator thingy
 */
package me.hwiggy.whmjava.payload.g;

import me.hwiggy.whmjava.payload.Payload;

/**
 * This class and its methods directly relate to the API documentation.
 * API documentation can be found at the￼ following URL:
 ￼* https://developers.whmcs.com/api-reference/getclients/
 */
public class GetClientsPayload extends Payload {

    /*
     * Obtain the Clients that match passed criteria
     */
    public GetClientsPayload() {
        super ("GetClients");
    }

    /***
     *
     * @param limitStart  The offset for the returned log data (default: 0)
     */
    public GetClientsPayload withLimitStart(int limitStart) {
        put("limitstart", limitStart);

        return this;
    }

    /***
     *
     * @param limitNum The number of records to return (default: 25)
     */
    public GetClientsPayload withLimitnum(int limitNum) {
        put("limitnum", limitNum);

        return this;
    }

    /***
     *
     * @param sorting The direction to sort the results. ASC or DESC. Default: ASC
     */
    public GetClientsPayload withSorting(String sorting) {
        put("sorting", sorting);

        return this;
    }

    /***
     *
     * @param search The search term to look for at the start of email, firstname, lastname, fullname or companyname
     */
    public GetClientsPayload withSearch(String search) {
        put("search", search);

        return this;
    }
}