/**
 * Generated by ramidzkh's awesome generator thingy
 */
package me.hwiggy.whmjava.payload.g;

import me.hwiggy.whmjava.payload.Payload;

/***
 * This class and its methods directly relate to the API documentation.
 * API documentation can be found at the￼ following URL:
 ￼* https://developers.whmcs.com/api-reference/gethealthstatus/
 */
public class GetHealthStatusPayload extends Payload {

    /*
     * Get health status.
     */
    public GetHealthStatusPayload() {
        super ("GetHealthStatus");
    }

    /***
     *
     * @param fetchStatus Pass as true to attempt to fetch server status values.
     */
    public GetHealthStatusPayload withFetchStatus(boolean fetchStatus) {
        put("fetchStatus", fetchStatus);

        return this;
    }
}