/**
 * Generated by ramidzkh's awesome generator thingy
 */
package me.hwiggy.whmjava.payload.g;

import me.hwiggy.whmjava.payload.Payload;

/***
 * This class and its methods directly relate to the API documentation.
 * API documentation can be found at the￼ following URL:
 ￼* https://developers.whmcs.com/api-reference/getinvoice/
 */
public class GetInvoicePayload extends Payload {

    /***
     * Retrieve a specific invoice
     * @param invoiceID The ID of the invoice to retrieve
     */
    public GetInvoicePayload(int invoiceID) {
        super ("GetInvoice");
        put("invoiceid", invoiceID);
    }
}