/**
 * Generated by ramidzkh's awesome generator thingy
 */
package me.hwiggy.whmjava.payload.g;

import me.hwiggy.whmjava.payload.Payload;

/***
 * This class and its methods directly relate to the API documentation.
 * API documentation can be found at the￼ following URL:
 ￼* https://developers.whmcs.com/api-reference/getmoduleconfigurationparameters/
 */
public class GetModuleConfigurationParametersPayload extends Payload {

    /***
     * Obtains the Module Configuration Parameters
     * @param moduleType The module type to be activated
     * @param moduleName The module name to be activated
     */
    public GetModuleConfigurationParametersPayload(String moduleType, String moduleName) {
        super ("GetModuleConfigurationParameters");
        put("moduleType", moduleType);
        put("moduleName", moduleName);
    }
}