/**
 * Generated by ramidzkh's awesome generator thingy
 */
package me.hwiggy.whmjava.payload.g;

import me.hwiggy.whmjava.payload.Payload;

/***
 * This class and its methods directly relate to the API documentation.
 * API documentation can be found at the￼ following URL:
 ￼* https://developers.whmcs.com/api-reference/getmodulequeue/
 */
public class GetModuleQueuePayload extends Payload {

    /*
     * Obtains the Module Queue for Incomplete Failed Actions
     */
    public GetModuleQueuePayload() {
        super ("GetModuleQueue");
    }

    /***
     *
     * @param serviceType The type of service to load (‘domain’, ‘service’ or “))
     */
    public GetModuleQueuePayload withServiceType(String serviceType) {
        append("serviceType", serviceType);

        return this;
    }

    /***
     *
     * @param moduleName The module name to obtain the queue for in system format. eg cpanel
     */
    public GetModuleQueuePayload withModuleName(String moduleName) {
        append("moduleName", moduleName);

        return this;
    }

    /***
     *
     * @param moduleAction The module action to obtain the queue for. eg CreateAccount, SuspendAccount
     */
    public GetModuleQueuePayload withModuleAction(String moduleAction) {
        append("moduleAction", moduleAction);

        return this;
    }

    /***
     *
     * @param since The date/time since to obtain the items. Format Y-m-d Can include H:i:s
     */
    public GetModuleQueuePayload withSince(String since) {
        append("since", since);

        return this;
    }
}