/**
 * Generated by ramidzkh's awesome generator thingy
 */
package me.hwiggy.whmjava.payload.g;

import me.hwiggy.whmjava.payload.Payload;

/***
 * This class and its methods directly relate to the API documentation.
 * API documentation can be found at the￼ following URL:
 ￼* https://developers.whmcs.com/api-reference/getproject/
 */
public class GetProjectPayload extends Payload {

    /***
     * Retrieve a specific Project
     * @param projectid The project id to obtain
     */
    public GetProjectPayload(int projectid) {
        super ("GetProject");
        put("projectid", projectid);
    }
}