/**
 * Generated by ramidzkh's awesome generator thingy
 */
package me.hwiggy.whmjava.payload.g;

import me.hwiggy.whmjava.payload.Payload;

/***
 * This class and its methods directly relate to the API documentation.
 * API documentation can be found at the￼ following URL:
 ￼* https://developers.whmcs.com/api-reference/getpromotions/
 */
public class GetPromotionsPayload extends Payload {

    /*
     * Obtain promotions matching the passed criteria
     */
    public GetPromotionsPayload() {
        super ("GetPromotions");
    }

    /***
     *
     * @param code Retrieve a specific promotion code. Do not pass to retrieve all
     */
    public GetPromotionsPayload withCode(String code) {
        put("code", code);

        return this;
    }
}