/**
 * Generated by ramidzkh's awesome generator thingy
 */
package me.hwiggy.whmjava.payload.g;

import me.hwiggy.whmjava.payload.Payload;

/***
 * This class and its methods directly relate to the API documentation.
 * API documentation can be found at the￼ following URL:
 ￼* https://developers.whmcs.com/api-reference/getstats/
 */
public class GetStatsPayload extends Payload {

    /*
     * Obtain system statistics
     */
    public GetStatsPayload() {
        super ("GetStats");
    }
}