/**
 * Generated by ramidzkh's awesome generator thingy
 */
package me.hwiggy.whmjava.payload.g;

import me.hwiggy.whmjava.payload.Payload;

/***
 * This class and its methods directly relate to the API documentation.
 * API documentation can be found at the￼ following URL:
 ￼* https://developers.whmcs.com/api-reference/getstaffonline/
 */
public class GetStaffOnlinePayload extends Payload {

    /*
     * Retrieve a list of currently logged in admin users.
     */
    public GetStaffOnlinePayload() {
        super ("GetStaffOnline");
    }
}