/**
 * Generated by ramidzkh's awesome generator thingy
 */
package me.hwiggy.whmjava.payload.g;

import me.hwiggy.whmjava.payload.Payload;

/***
 * This class and its methods directly relate to the API documentation.
 * API documentation can be found at the￼ following URL:
 ￼* https://developers.whmcs.com/api-reference/getsupportdepartments/
 */
public class GetSupportDepartmentsPayload extends Payload {

    /*
     * Get the support departments and associated ticket counts
     */
    public GetSupportDepartmentsPayload() {
        super ("GetSupportDepartments");
    }

    /***
     *
     * @param ignore_dept_assignments Pass as true to not adhere to the departments the API user is a member of.
     */
    public GetSupportDepartmentsPayload withIgnore_dept_assignments(boolean ignore_dept_assignments) {
        put("ignore_dept_assignments", ignore_dept_assignments);

        return this;
    }
}