/**
 * Generated by ramidzkh's awesome generator thingy
 */
package me.hwiggy.whmjava.payload.g;

import me.hwiggy.whmjava.payload.Payload;

/***
 * This class and its methods directly relate to the API documentation.
 * API documentation can be found at the￼ following URL:
 ￼* https://developers.whmcs.com/api-reference/getsupportstatuses/
 */
public class GetSupportStatusesPayload extends Payload {

    /*
     * Get the support statuses and number of tickets in each status
     */
    public GetSupportStatusesPayload() {
        super ("GetSupportStatuses");
    }

    /***
     *
     * @param deptid Obtain counts for a specific department id
     */
    public GetSupportStatusesPayload withDeptid(int deptid) {
        put("deptid", deptid);

        return this;
    }
}