/**
 * Generated by ramidzkh's awesome generator thingy
 */
package me.hwiggy.whmjava.payload.g;

import me.hwiggy.whmjava.payload.Payload;

/***
 * This class and its methods directly relate to the API documentation.
 * API documentation can be found at the￼ following URL:
 ￼* https://developers.whmcs.com/api-reference/gettodoitems/
 */
public class GetToDoItemsPayload extends Payload {

    /*
     * Get To-Do List Items.
     */
    public GetToDoItemsPayload() {
        super ("GetToDoItems");
    }


    /***
     *
     * @param limitStart The offset for the returned log data (default: 0)
     */
    public GetToDoItemsPayload withLimitstart(int limitStart) {
        append("limitstart", limitStart);

        return this;
    }

    /***
     *
     * @param limitNum The number of records to return (default: 25)
     */
    public GetToDoItemsPayload withLimitNum(int limitNum) {
        append("limitnum", limitNum);

        return this;
    }

    /***
     *
     * @param status Status to filter for. Possible values include: Incomplete, New, Pending, In Progress, Completed
     */
    public GetToDoItemsPayload withStatus(String status) {
        append("status", status);

        return this;
    }
}