/**
 * Generated by ramidzkh's awesome generator thingy
 */
package me.hwiggy.whmjava.payload.g;

import me.hwiggy.whmjava.payload.Payload;

/***
 * This class and its methods directly relate to the API documentation.
 * API documentation can be found at the￼ following URL:
 ￼* https://developers.whmcs.com/api-reference/getticketcounts/
 */
public class GetTicketCountsPayload extends Payload {

    /*
     * Get ticket counts.
     */
    public GetTicketCountsPayload() {
        super ("GetTicketCounts");
    }

    /***
     *
     * @param ignoreDepartmentAssignments Pass as true to not adhere to the departments the API user is a member of.
     */
    public GetTicketCountsPayload withIgnoreDepartmentAssignments(boolean ignoreDepartmentAssignments) {
        put("ignoreDepartmentAssignments", ignoreDepartmentAssignments);

        return this;
    }

    /***
     *
     * @param includeCountsByStatus Pass as true to not adhere to the departments the API user is a member of.
     */
    public GetTicketCountsPayload withIncludeCountsByStatus(boolean includeCountsByStatus) {
        put("includeCountsByStatus", includeCountsByStatus);

        return this;
    }
}