/**
 * Generated by ramidzkh's awesome generator thingy
 */
package me.hwiggy.whmjava.payload.g;

import me.hwiggy.whmjava.payload.Payload;

/***
 * This class and its methods directly relate to the API documentation.
 * API documentation can be found at the￼ following URL:
 ￼* https://developers.whmcs.com/api-reference/getticketnotes/
 */
public class GetTicketNotesPayload extends Payload {

    /***
     * Obtain a specific ticket notes
     * @param ticketid Obtain the ticket for the specific ticket id
     */
    public GetTicketNotesPayload(int ticketid) {
        super ("GetTicketNotes");
        put("ticketid", ticketid);
    }
}