/**
 * Generated by ramidzkh's awesome generator thingy
 */
package me.hwiggy.whmjava.payload.g;

import me.hwiggy.whmjava.payload.Payload;

/***
 * This class and its methods directly relate to the API documentation.
 * API documentation can be found at the￼ following URL:
 ￼* https://developers.whmcs.com/api-reference/gettransactions/
 */
public class GetTransactionsPayload extends Payload {

    /*
     * Obtain transactions matching the passed criteria
     */
    public GetTransactionsPayload() {
        super ("GetTransactions");
    }

    /***
     *
     * @param invoiceID Obtain transactions for a specific invoice id
     */
    public GetTransactionsPayload withInvoiceID(int invoiceID) {
        put("invoiceid", invoiceID);

        return this;
    }

    /***
     *
     * @param clientID Find transactions for a specific client id
     */
    public GetTransactionsPayload withClientID(int clientID) {
        put("clientid", clientID);

        return this;
    }

    /***
     *
     * @param transID Find transactions for a specific transaction id
     */
    public GetTransactionsPayload withTransID(String transID) {
        put("transid", transID);

        return this;
    }
}