/**
 * Generated by ramidzkh's awesome generator thingy
 */
package me.hwiggy.whmjava.payload.g;

import me.hwiggy.whmjava.payload.Payload;

/***
 * This class and its methods directly relate to the API documentation.
 * API documentation can be found at the￼ following URL:
 ￼* https://developers.whmcs.com/api-reference/gettickets/
 */
public class GetTicketsPayload extends Payload {

    /*
     * Obtain tickets matching the passed criteria
     */
    public GetTicketsPayload() {
        super ("GetTickets");
    }


    /***
     *
     * @param limitStart The offset for the returned quote data (default: 0)
     */
    public GetTicketsPayload withLimitStart(int limitStart) {
        put("limitstart", limitStart);

        return this;
    }

    /***
     *
     * @param limitNum The number of records to return (default: 25)
     */
    public GetTicketsPayload withLimitNum(int limitNum) {
        put("limitnum", limitNum);

        return this;
    }

    /***
     *
     * @param deptId Obtain tickets in a specific department
     */
    public GetTicketsPayload withDeptId(int deptId) {
        put("deptid", deptId);

        return this;
    }

    /***
     *
     * @param clientid Find tickets for a specific client id
     */
    public GetTicketsPayload withClientid(int clientid) {
        put("clientid", clientid);

        return this;
    }

    /***
     *
     * @param email Find tickets for a specific non-client email address
     */
    public GetTicketsPayload withEmail(String email) {
        put("email", email);

        return this;
    }

    /***
     *
     * @param status Find tickets matching a specific status. Any configured status plus: Awaiting Reply, All Active Tickets, My Flagged Tickets
     */
    public GetTicketsPayload withStatus(String status) {
        put("status", status);

        return this;
    }

    /***
     *
     * @param subject Find tickets containing a specific subject - uses approximate string matching.
     */
    public GetTicketsPayload withSubject(String subject) {
        put("subject", subject);

        return this;
    }

    /***
     *
     * @param ignore_dept_assignments Pass as true to not adhere to the departments the API user is a member of.
     */
    public GetTicketsPayload withIgnore_dept_assignments(boolean ignore_dept_assignments) {
        put("ignore_dept_assignments", ignore_dept_assignments);

        return this;
    }
}