/**
 * Generated by ramidzkh's awesome generator thingy
 */
package me.hwiggy.whmjava.payload.d;

import me.hwiggy.whmjava.payload.Payload;

/***
 * This class and its methods directly relate to the API documentation.
 * API documentation can be found at the￼ following URL:
 ￼* https://developers.whmcs.com/api-reference/deletequote/
 */
public class DeleteQuotePayload extends Payload {

    /***
     * Deletes a quote.
     * @param quoteID The quote id to be deleted
     */
    public DeleteQuotePayload(int quoteID) {
        super ("DeleteQuote");
        put("quoteid", quoteID);
    }
}
