/**
 * Generated by ramidzkh's awesome generator thingy
 */
package me.hwiggy.whmjava.payload.d;

import me.hwiggy.whmjava.payload.Payload;

/***
 * This class and its methods directly relate to the API documentation.
 * API documentation can be found at the￼ following URL:
 ￼* https://developers.whmcs.com/api-reference/deleteticketnote/
 */
public class DeleteTicketNotePayload extends Payload {

    /*
     * Deletes a ticket note.
     * @param noteID The ticket note to be deleted
     */
    public DeleteTicketNotePayload(int noteID) {
        super ("DeleteTicketNote");
        put("noteid", noteID);
    }
}
