/**
 * Generated by ramidzkh's awesome generator thingy
 */
package me.hwiggy.whmjava.payload.d;

import me.hwiggy.whmjava.payload.Payload;

/***
 * This class and its methods directly relate to the API documentation.
 * API documentation can be found at the￼ following URL:
 ￼* https://developers.whmcs.com/api-reference/domaintoggleidprotect/
 */
public class DomainToggleIdProtectPayload extends Payload {

    /***
     * Sends the Toggle ID Protect command to the registrar for the domain
     * @param domainid The id of the domain to toggle ID Protection for
     */
    public DomainToggleIdProtectPayload(int domainid) {
        super ("DomainToggleIdProtect");
        put("domainid", domainid);
    }

    /***
     *
     * @param IDprotect Should ID Protection be turned on
     */
    public DomainToggleIdProtectPayload withIDprotect(boolean IDprotect) {
        put("idprotect", IDprotect);

        return this;
    }
}
