/**
 * Generated by ramidzkh's awesome generator thingy
 */
package me.hwiggy.whmjava.payload.d;

import me.hwiggy.whmjava.payload.Payload;

/***
 * This class and its methods directly relate to the API documentation.
 * API documentation can be found at the￼ following URL:
 ￼* https://developers.whmcs.com/api-reference/domaingetlockingstatus/
 */
public class DomainGetLockingStatusPayload extends Payload {

    /***
     * Obtains the current lock status of the domain.
     * @param domainID The id of the domain to obtain the lock status for
     */
    public DomainGetLockingStatusPayload(int domainID) {
        super ("DomainGetLockingStatus");
        put("domainid", domainID);
    }
}
