/**
 * Generated by ramidzkh's awesome generator thingy
 */
package me.hwiggy.whmjava.payload.d;

import me.hwiggy.whmjava.payload.Payload;

/***
 * This class and its methods directly relate to the API documentation.
 * API documentation can be found at the￼ following URL:
 ￼* https://developers.whmcs.com/api-reference/domainupdatenameservers/
 */
public class DomainUpdateNameserversPayload extends Payload {

    /***
     * Sends the Save Nameservers command to the registrar for the domain
     * @param ns1 The first nameserver
     * @param ns2 The second nameserver
     */
    public DomainUpdateNameserversPayload(String ns1, String ns2) {
        super ("DomainUpdateNameservers");
        put("ns1", ns1);
        put("ns2", ns2);
    }

    /***
     *
     * @param domainid The id of the domain to update the nameservers for recommended
     */
    public DomainUpdateNameserversPayload withDomainid(int domainid) {
        put("domainid", domainid);

        return this;
    }

    /***
     *
     * @param domain The domain name to be update the nameservers for. This or $domainid is required
     */
    public DomainUpdateNameserversPayload withDomain(String domain) {
        put("domain", domain);

        return this;
    }

    /***
     *
     * @param ns1 The first nameserver
     */
    public DomainUpdateNameserversPayload withNS1(String ns1) {
        put("ns3", ns1);

        return this;
    }

    /***
     *
     * @param ns2 The second nameserver
     */
    public DomainUpdateNameserversPayload withNS2(String ns2) {
        put("ns4", ns2);

        return this;
    }

    /***
     *
     * @param ns3 The third nameserver
     */
    public DomainUpdateNameserversPayload withNS3(String ns3) {
        put("ns3", ns3);

        return this;
    }

    /***
     *
     * @param ns4 The fourth nameserver
     */
    public DomainUpdateNameserversPayload withNS4(String ns4) {
        put("ns4", ns4);

        return this;
    }

    /***
     *
     * @param ns5 The fifth nameserver
     */
    public DomainUpdateNameserversPayload withNS5(String ns5) {
        put("ns5", ns5);

        return this;
    }
}
