/**
 * Generated by ramidzkh's awesome generator thingy
 */
package me.hwiggy.whmjava.payload.d;

import me.hwiggy.whmjava.payload.Payload;

/***
 * This class and its methods directly relate to the API documentation.
 * API documentation can be found at the￼ following URL:
 ￼* https://developers.whmcs.com/api-reference/domainrequestepp/
 */
public class DomainRequestEPPPayload extends Payload {

    /***
     * Sends the Request EPP command to the registrar for the domain
     * @param domainID The id of the domain to obtain the EPP for
     */
    public DomainRequestEPPPayload(int domainID) {
        super ("DomainRequestEPP");
        put("domainid", domainID);
    }
}
