/**
 * Generated by ramidzkh's awesome generator thingy
 */
package me.hwiggy.whmjava.payload.d;

import me.hwiggy.whmjava.payload.Payload;

/***
 * This class and its methods directly relate to the API documentation.
 * API documentation can be found at the￼ following URL:
 ￼* https://developers.whmcs.com/api-reference/domainrelease/
 */
public class DomainReleasePayload extends Payload {

    /***
     * Sends the Release command to the registrar for the domain to a new tag
     * @param newtag The receiving tag for the domain
     */
    public DomainReleasePayload(String newtag) {
        super ("DomainRelease");
        put("newtag", newtag);
    }

    /***
     *
     * @param domainID The id of the domain to be released recommended
     */
    public DomainReleasePayload withDomainID(int domainID) {
        put("domainid", domainID);

        return this;
    }

    /***
     *
     * @param domain The domain name to be released. This or $domainid is required
     */
    public DomainReleasePayload withDomain(String domain) {
        put("domain", domain);

        return this;
    }
}
