/**
 * Generated by ramidzkh's awesome generator thingy
 */
package me.hwiggy.whmjava.payload.d;

import me.hwiggy.whmjava.payload.Payload;

/***
 * This class and its methods directly relate to the API documentation.
 * API documentation can be found at the￼ following URL:
 ￼* https://developers.whmcs.com/api-reference/domaintransfer/
 */
public class DomainTransferPayload extends Payload {

    /*
     * Sends the Transfer command to the registrar for the domain
     */
    public DomainTransferPayload() {
        super ("DomainTransfer");
    }

    /***
     *
     * @param domainID The id of the domain to be transferred recommended
     */
    public DomainTransferPayload withDomainID(int domainID) {
        put("domainid", domainID);

        return this;
    }

    /***
     *
     * @param domain The domain name to be transferred. This or $domainid is required
     */
    public DomainTransferPayload withDomain(String domain) {
        put("domain", domain);

        return this;
    }

    /***
     *
     * @param eppcode Provide a new EPP Code for the Transfer Request
     */
    public DomainTransferPayload withEppcode(int eppcode) {
        put("eppcode", eppcode);

        return this;
    }
}