/**
 * Generated by ramidzkh's awesome generator thingy
 */
package me.hwiggy.whmjava.payload.d;

import me.hwiggy.whmjava.payload.Payload;

/**
 * This class and its methods directly relate to the API documentation.
 * API documentation can be found at the￼ following URL:
 ￼* https://developers.whmcs.com/api-reference/domainregister/
 */
public class DomainRegisterPayload extends Payload {

    /*
     * Sends the Register command to the registrar for the domain
     */
    public DomainRegisterPayload() {
        super ("DomainRegister");
    }


    /***
     *
     * @param domainid The id of the domain to register recommended
     */
    public DomainRegisterPayload withDomainid(int domainid) {
        put("domainid", domainid);

        return this;
    }

    /***
     *
     * @param domain The domain name to be registered. This or $domainid is required
     */
    public DomainRegisterPayload withDomain(String domain) {
        put("domain", domain);

        return this;
    }
}