/**
 * Generated by ramidzkh's awesome generator thingy
 */
package me.hwiggy.whmjava.payload.d;

import me.hwiggy.whmjava.payload.Payload;

/***
 * This class and its methods directly relate to the API documentation.
 * API documentation can be found at the￼ following URL:
 ￼* https://developers.whmcs.com/api-reference/domainwhois/
 */
public class DomainWhoisPayload extends Payload {

    /***
     * Retrieve domain whois information.
     * @param domain The domain name to lookup
     */
    public DomainWhoisPayload(String domain) {
        super ("DomainWhois");
        put("domain", domain);
    }
}
