/**
 * Generated by ramidzkh's awesome generator thingy
 */
package me.hwiggy.whmjava.payload.e;

import me.hwiggy.whmjava.payload.Payload;

/***
 * This class and its methods directly relate to the API documentation.
 * API documentation can be found at the￼ following URL:
 ￼* https://developers.whmcs.com/api-reference/encryptpassword/
 */
public class EncryptPasswordPayload extends Payload {

    /***
     * Encrypt a string.
     * @param password2 The string to encrypt
     */
    public EncryptPasswordPayload(String password2) {
        super ("EncryptPassword");
        put("password2", password2);
    }
}
